/**
 * Copies third-party runtime assets into the package: GSAP's ESM build (a private instance, no window globals)
 * and the Tactile fonts. Run after changing their versions: `npm run vendor`. The output is committed.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { root } from "./package-files.mjs";

const modules = join(root, "node_modules");

// --- GSAP: follow relative imports from the entry points we use.
const gsapSrc = join(modules, "gsap");
const gsapOut = join(root, "scripts/vendor/gsap");
rmSync(gsapOut, { recursive: true, force: true });
const pending = ["index.js", "Flip.js", "CustomEase.js"];
const copied = new Set();
while (pending.length) {
  const file = pending.pop();
  if (copied.has(file)) continue;
  copied.add(file);
  // Plugins self-register into whatever `window.gsap` another module exposed; ours register explicitly instead.
  const source = readFileSync(join(gsapSrc, file), "utf8")
    .replace(/^typeof window !== "undefined" && window\.gsap && window\.gsap\.registerPlugin\(\w+\);$/m, "")
    .replace(/^_getGSAP\(\) && gsap\.registerPlugin\(\w+\);$/m, "");
  mkdirSync(dirname(join(gsapOut, file)), { recursive: true });
  writeFileSync(join(gsapOut, file), source);
  for (const [, spec] of source.matchAll(/from\s+["'](\.[^"']+)["']/g)) {
    pending.push(join(dirname(file), spec).replace(/\\/g, "/"));
  }
}
const gsapPkg = JSON.parse(readFileSync(join(gsapSrc, "package.json"), "utf8"));
writeFileSync(
  join(gsapOut, "LICENSE.md"),
  `# GSAP ${gsapPkg.version}\n\nCopied from the npm package \`gsap\` by tools/vendor.mjs.\n` +
    `License: ${gsapPkg.license ?? "see https://gsap.com/standard-license"}\n`,
);

// --- Fonts: keep the subsets the module's languages need.
const FONTS = [
  ["@fontsource-variable/onest", "onest"],
  ["@fontsource-variable/jetbrains-mono", "jetbrains-mono"],
  ["@fontsource-variable/unbounded", "unbounded"],
];
const SUBSETS = ["latin", "latin-ext", "cyrillic", "cyrillic-ext"];
const fontOut = join(root, "assets/fonts");
rmSync(fontOut, { recursive: true, force: true });
mkdirSync(fontOut, { recursive: true });
const rules = [];
for (const [pkg, slug] of FONTS) {
  const dir = join(modules, pkg);
  const css = readFileSync(join(dir, "index.css"), "utf8");
  for (const block of css.split(/(?=\/\*)/)) {
    const subset = SUBSETS.find((s) => block.startsWith(`/* ${slug}-${s}-wght-normal */`));
    if (!subset) continue;
    const [, file] = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/) ?? [];
    if (!file) continue;
    cpSync(join(dir, "files", file), join(fontOut, file));
    rules.push(
      block
        .trim()
        .replace(/url\(\.\/files\/([^)]+\.woff2)\)/, "url(../../assets/fonts/$1)")
        .replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/, ""),
    );
  }
  const license = ["LICENSE", "LICENSE.md", "OFL.txt"].map((n) => join(dir, n)).find(existsSync);
  if (license) cpSync(license, join(fontOut, `OFL-${slug}.txt`));
}
mkdirSync(join(root, "styles/tactile"), { recursive: true });
writeFileSync(
  join(root, "styles/tactile/fonts.css"),
  `/* Generated by tools/vendor.mjs from @fontsource-variable. Loaded only while the "useWebFonts" setting is on. */\n${rules.join("\n\n")}\n`,
);
console.log(`vendored ${copied.size} GSAP files and ${rules.length} font faces`);
